---
title: Development Process
---
gitGraph
   commit id: "Feature A"
   commit id: "Feature B"
   branch feature-c
   checkout feature-c
   commit
   commit
   checkout main
   merge feature-c id: "Feature C" type: HIGHLIGHT
   commit id: "Feature D"
   commit id: "Feature E"