services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    command: --quiet
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONOG_PASS}
    volumes:
      - data:/data/db
    networks:
      - aeon-net
    labels:
      - "logging=alloy"
      - "loki_job=mongodb"
      - "loki_env=production"

  bitauth1:
    image: ghcr.io/teambitvictory/bitauth:release
    environment:
      - MONGO_URL=mongodb:27017
      - MONGO_USER=${MONGO_USER}
      - MONOG_PASS=${MONOG_PASS}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy:4317/
      - OTEL_METRICS_EXPORTER=none
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ONLY_ADMIN_REGISTRATION=true
    networks:
      - aeon-net
    pull_policy: always
    labels:
      - "logging=alloy"
      - "loki_job=bitauth"
      - "loki_env=production"

  aeon1:
    image: ghcr.io/djochim/cs_se_project:main
    environment:
      - MONGO_URL=mongodb:27017
      - MONGO_USER=${MONGO_USER}
      - MONOG_PASS=${MONOG_PASS}
      - OPEN_API_KEY=${OPEN_API_KEY}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy:4317/
      - OTEL_METRICS_EXPORTER=none
    networks:
      - aeon-net
    pull_policy: always
    labels:
      - "logging=alloy"
      - "loki_job=aeon"
      - "loki_env=production"

  ngnix-proxy:
    image: nginx:1.27.4-alpine
    ports:
      - "443:443"
    networks:
      - aeon-net
    restart: always
    volumes:
      - type: bind
        source: /etc/nginx/certs
        target: /etc/nginx/certs
        read_only: true
      - type: bind
        source: /etc/nginx/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
    labels:
      - "logging=alloy"
      - "loki_job=ngnix"
      - "loki_env=production"

  alloy:
    image: grafana/alloy:latest
    command: [
      "run",
      "/etc/alloy/config.alloy",
    ]
    restart: always
    environment:
      - OTEL_USERNAME=1157398
      - FLEET_USERNAME=1157398
      - LOKI_USERNAME=1115197
      - PROMETHEUS_USERNAME=2239039
      - GRAFANA_CLOUD_API_KEY=${GRAFANA_CLOUD_API_KEY}
    networks:
      - aeon-net
    volumes:
      - type: bind
        source: ./monitoring/alloy.conf
        target: /etc/alloy/config.alloy
        read_only: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    labels:
      - "logging=alloy"
      - "loki_job=alloy"
      - "loki_env=production"

networks:
  aeon-net:

volumes:
  data:
