---
title: Epic dependency graph
---
flowchart LR
   a[Setup Cloud Server] --> b[Nutritional Assistant chat] & c[User management] --> A@{ shape: flag, label: "First Release with a usable version"} --> e[User recipe store]