version: '3'
services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - data:/data/db

  aeon:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MONGO_URL=mongodb:27017
      - MONGO_INITDB_ROOT_PASSWORD=pass
    networks:
      - aeon


networks:
  aeon:


volumes:
  data: