version: '3'
services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - data:/data/db
    networks:
      - aeon

  bitauth:
    image: ghcr.io/teambitvictory/bitauth:release
    ports:
      - "8070:8070"
    environment:
      - MONGO_URL=mongodb:27017
      - MONGO_USER=user
      - MONOG_PASS=pass
      - ONLY_ADMIN_REGISTRATION=true
    networks:
      - aeon


networks:
  aeon:


volumes:
  data: