name: User Story
description: File a bug report.
title: "[STORY]: "
labels: ["story"]
projects: ["djochim/1"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Short explanation of what the story is about and why it matters
  - type: input
    id: as
    attributes:
      label: As a
      placeholder: user / persona
  - type: input
    id: want
    attributes:
      label: I want
      placeholder: feature or functionality
  - type: input
    id: that
    attributes:
      label: so that
      placeholder: benefit or goal
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: List the conditions that must be met for this story to be considered complete
