---
title: Assistance Process
---
sequenceDiagram
   participant User
   box LightGreen Aeon
   participant App as Android/iOS App
   participant Backend
   participant DB as Mongo DB
   end
   participant OpenAI as Open AI
   User->>+App: Ask first question
   App->>+Backend: Creates a new conversation session
   Backend ->> DB: Saves conversation details
   Backend ->> OpenAI: Creates new Thread
   Backend ->> OpenAI: Runs Assistant on Thread
   par Background Job
      loop until thread run is finished
       OpenAI ->> Backend: send updates on Thread
       Backend ->> DB: Updates conversation with updates
      end
    and
      Backend ->>- App: Returns conversation details
    end
   App->>-User: Shows conversation
   loop until conversation closed
      activate App
      App ->>+ Backend: Get messages from conversation
      Backend ->>+ DB: Get messages from conversation
      DB -->>- Backend: Returns messages
      Backend ->>- App: Returns messages
      App -->>- User: Shows conversation
   end
   User->>+App: Ask next question
   App->>+Backend: Add message to conversation
   Backend ->> OpenAI: Add message to Thread
   Backend ->> OpenAI: Runs Assistant on Thread
   Backend ->> DB: Updates conversation with new messages
   par Background Job
      loop until thread run is finished
       OpenAI -->> Backend: Get new messages from Thread
       Backend ->> DB: Updates conversation with new messages
      end
    and
      Backend ->>- App: Returns conversation details
    end
    deactivate App
